name: Bug Report
description: Report a bug in the application
projects:
  - CodeSparkApp/1
body:
- type: markdown
  attributes:
    value: "## Bug Report\nPlease fill out the following details to help us diagnose and fix the issue efficiently."

- type: textarea
  attributes:
    label: Bug Description
    description: "Provide a detailed description of the bug"
    placeholder: "When I ... the application ... instead of ..."
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: "List the steps required to reproduce the bug"
    placeholder: |
      1. Open the application
      2. Click on ...
      3. Observe the issue...
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Information
    description: "Any other details that might help diagnose the issue"
