name: Task
description: Creating a new task
projects:
  - CodeSparkApp/1
body:
- type: markdown
  attributes:
    value: "## Task\nPlease fill out the following details to help us effectively plan and execute the task."

- type: textarea
  attributes:
    label: Task Description
    description: "Provide a detailed description of the task."
    placeholder: "As a ... I need ... so that I ..."
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ## Acceptance Criteria
        - [ ] Criteria 1
        - [ ] Criteria 2

- type: textarea
  attributes:
    label: Additional Information
    description: "Any other details to help complete the task"
